name: Rustfmt

on: [push]

jobs:
  build:
    runs-on: [self-hosted, linux, x64, netcup, general]

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy, rustfmt
      - name: Run rustfmt
        run: make format-check
